# Run by typing:
# snakemake all
# For dry run type:
# snakemake all -n

# Cstree model
pattern_cstree = "cstree/cstree_p={cstree_p}/cstree_max_cvar={cstree_max_cvar}/cstree_prob_cvar={cstree_prob_cvar}/seed={seed}"
pattern_cstree_params = "true_cstree_params/cstree_params_alpha={cstree_params_alpha}/seed={seed}"
pattern_cstree_data = "data/cstree_data_n={cstree_data_n}/seed={seed}"

# Structure learning
pattern_cslearn = ("cslearn/cslearn_poss_cvars={cslearn_poss_cvars}/cslearn_mcmc_iterations={cslearn_mcmc_iterations}/"
                   "cslearn_alpha_tot={cslearn_alpha_tot}/cslearn_param_prior={cslearn_param_prior}/"
                   "cslearn_max_cvar={cslearn_max_cvar}/cslearn_prob_cvar={cslearn_prob_cvar}/seed={seed}")
pattern_grasp = "grasp/seed={seed}"
pattern_pc = "pc/pc_alpha={pc_alpha}/seed={seed}"
pattern_bos = "bos/seed={seed}"
pattern_bhc = "bhc/bhc_start_alg={bhc_start_alg}/seed={seed}"

# Structure learning with imposed start algorithm pattern
pattern_grasp_bhc = "bhc/bhc_start_alg="+ pattern_grasp +"/seed={seed}"
pattern_pc_bhc = "bhc/bhc_start_alg="+pattern_pc +"/seed={seed}"

# With imposed poss_cvars
pattern_pc_cslearn = ("cslearn/cslearn_poss_cvars="+pattern_pc+"/cslearn_mcmc_iterations={cslearn_mcmc_iterations}/"
                      "cslearn_alpha_tot={cslearn_alpha_tot}/cslearn_param_prior={cslearn_param_prior}/"
                      "cslearn_max_cvar={cslearn_max_cvar}/cslearn_prob_cvar={cslearn_prob_cvar}/seed={seed}")
pattern_grasp_cslearn = ("cslearn/cslearn_poss_cvars="+pattern_grasp+"/cslearn_mcmc_iterations={cslearn_mcmc_iterations}/"
                         "cslearn_alpha_tot={cslearn_alpha_tot}/cslearn_param_prior={cslearn_param_prior}/"
                         "cslearn_max_cvar={cslearn_max_cvar}/cslearn_prob_cvar={cslearn_prob_cvar}/seed={seed}")

# Parameter estimation
pattern_dag_param_est = "dag_param_est/dag_param_est_estimation_type={dag_param_est_estimation_type}/dag_param_est_alpha={dag_param_est_alpha}/seed={seed}" # type is bdeu or mle
pattern_cstree_param_est = "cstree_param_est/cstree_param_est_estimation_type={cstree_param_est_estimation_type}/cstree_param_est_alpha={cstree_param_est_alpha}/seed={seed}" # type is bdeu or mle
pattern_st_param_est = "st_param_est/st_param_est_estimation_type={st_param_est_estimation_type}/st_param_est_alpha={st_param_est_alpha}/seed={seed}" # type is bdeu or mle

# Evaluation
pattern_kl_div = "kl_div"


def input_cvars(wildcards):
    """
    Input for the poss_cvars parameter of the cslearn algorithm
    """

    if wildcards.cslearn_poss_cvars == "None":
        return []
    else:
        # the poss_cvars will be the pattern string of a DAG estimation algorithm
        return ("estimate" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + wildcards.cslearn_poss_cvars +
                "/poss_cvars.json")

def input_alg(wildcards):

    if wildcards.bhc_start_alg == "None":
        return []
    else:
        # the poss_cvars will be the pattern string of a DAG estimation algorithm
        return ("estimate" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + wildcards.bhc_start_alg +
                "/structure.csv")

def input_time_bhc(wildcards):

        if wildcards.bhc_start_alg == "None":
            return []
        else:
            # the poss_cvars will be the pattern string of a DAG estimation algorithm
            return ("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + wildcards.bhc_start_alg +
                    "/time.csv")

def input_time_cslearn(wildcards):

        if wildcards.cslearn_poss_cvars == "None":
            return []
        else:
            # the poss_cvars will be the pattern string of a DAG estimation algorithm
            return ("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + wildcards.cslearn_poss_cvars +
                    "/time.csv")

rule all:
    input:
        "results/kl_divergence_2a.png",
        "results/kl_divergence_2b.png",
        "results/kl_divergence_2c.png",
        "results/time_3a.png",
        "results/time_3b.png"

rule cstree:           # tested
    # Calculate KL divergence between two distribution
    output:
        "true_cstree/"+ pattern_cstree + "/cstree.csv"
    script:
        "snake_scripts/generate_cstree.py"

rule cstree_params:     # untested
    input:
        cstree=rules.cstree.output
    output:
        ("true_cstree_params/"+pattern_cstree_params+
         "/true_cstree/"+ pattern_cstree + "/cstree.csv")
    script:
        "snake_scripts/generate_cstree_params.py"

rule full_true_cstree_distr:     # untested
    input:
        cstree=rules.cstree.output,
        cstree_params=rules.cstree_params.output
    output:
        ("full_true_distr/"+
         pattern_cstree+"/true_cstree_params/"+
         pattern_cstree_params+"/distr.csv")
    script:
        "snake_scripts/full_true_cstree_distr.py"

# this gives the whole cstree, but we split it into separate rules for consistency
rule cstree_data:             # tested
    # Simulate data from a distribution
    input:
        cstree=rules.cstree_params.output
    output:
        ("data"+
         "/true_cstree=/"+ pattern_cstree +
         "/true_cstree_params=/" + pattern_cstree_params +
         "/data=/"+pattern_cstree_data + "/data.csv")
    script:
        "snake_scripts/simulate_data.py"


rule bos:
    # Use BOS to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        rules.cstree_data.output
    output:
        bos_dag=("estimate" +
                 "/true_cstree=/" + pattern_cstree +
                 "/true_cstree_params=/" + pattern_cstree_params +
                 "/data=/" + pattern_cstree_data +
                 "/alg=/" + pattern_bos +
                 "/structure.csv"),

        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_bos +
              "/time.csv")
    script:
        "snake_scripts/estimate_bos.R"

rule bhc:
    # Use BHC to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        rules.cstree_data.output,
        input_alg=input_alg,
        input_time=input_time_bhc

    output:
        structure=("estimate" +
        "/true_cstree=/" + pattern_cstree +
        "/true_cstree_params=/" + pattern_cstree_params +
        "/data=/" + pattern_cstree_data +
        "/alg=/" + pattern_bhc +
        "/structure.csv"), # This might not be a csv file
        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_bhc +
              "/time.csv"),
        total_time=("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_bhc +
                    "/total_time.csv")
    script:
        "snake_scripts/estimate_bhc.R"

rule cslearn:           # untested
    # Estimate a distribution from data
    input:
        data=rules.cstree_data.output,
        poss_cvars=input_cvars, # will be empty if poss_cvars is None
        input_time=input_time_cslearn
    output:
        cstree = ("estimate" +
                  "/true_cstree=/" + pattern_cstree +
                  "/true_cstree_params=/" + pattern_cstree_params +
                  "/data=/" + pattern_cstree_data +
                  "/alg=/" + pattern_cslearn +
                  "/structure.csv"),
        #  add time and total time (including poss_csvars time)
        time = ("time" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + pattern_cslearn +
                "/time.csv"),
        total_time = ("time" +
                      "/true_cstree=/" + pattern_cstree +
                      "/true_cstree_params=/" + pattern_cstree_params +
                      "/data=/" + pattern_cstree_data +
                      "/alg=/" + pattern_cslearn +
                      "/total_time.csv") # this will be same as time if poss_cvars is None
    script:
        "snake_scripts/estimate_cstree.py"

rule grasp:            # tested
    # Use GRaSP to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        rules.cstree_data.output
    output:
        dag=("estimate" +
                   "/true_cstree=/" + pattern_cstree +
                   "/true_cstree_params=/" + pattern_cstree_params +
                   "/data=/" + pattern_cstree_data +
                   "/alg=/" + pattern_grasp +
                   "/structure.csv"), #
        cvars=("estimate" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + pattern_grasp +
                "/poss_cvars.json"),
        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_grasp +
              "/time.csv")
    script:
        "snake_scripts/estimate_grasp.py"

rule pc:               # tested
    # Use PC to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        rules.cstree_data.output
    output:
        dag=("estimate" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + pattern_pc +
                "/structure.csv"),
        cvars=("estimate" +
                  "/true_cstree=/" + pattern_cstree +
                  "/true_cstree_params=/" + pattern_cstree_params +
                  "/data=/" + pattern_cstree_data +
                  "/alg=/" + pattern_pc +
                  "/poss_cvars.json"),
        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_pc +
              "/time.csv")

    script:
        "snake_scripts/estimate_pc.py"

# The parameters fro the dag algorithms should be learned in separate rule,
# as this is done in R for both grasp and pc.
rule dag_bdeu_parameter_estimation:
    input:
        dag = ("estimate" +
                "/true_cstree=/{true_cstree}" +
                "/true_cstree_params=/{true_cstree_params}"
                "/data=/{data}" +
                "/alg=/{alg}" +
                "/structure.csv")
    output:
        dag_param_est=("dag_param_est" +
                       "/true_cstree=/{true_cstree}" +
                       "/true_cstree_params=/{true_cstree_params}" +
                       "/data=/{data}" +
                       "/alg=/{alg}" +
                       "/param_est=/"+pattern_dag_param_est +
                       "/params.csv")

# CS-BDeu
rule cstree_bdeu_parameter_estimation:
    input:
        cstree = rules.cslearn.output,
        data = rules.cstree_data.output
    output:
        param_est=("cstree_param_est" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_cslearn +
                    "/param_est=/"+pattern_cstree_param_est+
                    "/cstree.csv")
    script:
        "scripts/cstree_bdeu_parameter_estimation.R"

rule stagedtree_ml_parameter_estimation:
    input:
        ("estimate" +
        "/true_cstree=/" + pattern_cstree +
        "/true_cstree_params=/" + pattern_cstree_params +
        "/data=/" + pattern_cstree_data +
        "/alg=/{alg}" +
        "/structure.csv")
    output:
        param_est=("stagedtree_param_est" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/{alg}" +
                    "/param_est=/"+pattern_st_param_est+"/st.rds")

    script:
        "scripts/stagedtree_ml_parameter_estimation.R"

rule joint_stagedtree_distribution:
    input: # this coud be either bhc or bos
        input_st = ("stagedtree_param_est" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg_parameters}" +
                    "/param_est=/{param_est}" +
                    "/st.rds")
    output:
        full_distr=("full_distr" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg_parameters}" +
                    "/param_est=/{param_est}" +
                    "/distr.csv") # this needs to be matched better
    wildcard_constraints:
        alg_name = "bos|bhc"
    script:
        "snake_scripts/joint_stagedtree_distr.R"

rule joint_dag_distribution:    # untested
    # Estimate a distribution from data
    input:
        input_bn = ("dag_param_est" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg}" +
                    "/param_est=/{param_est}" +
                    "/params.csv")
    output:
        full_distr=("full_distr" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg}" +
                    "/param_est=/{param_est}" +
                    "/distr.csv")
    wildcard_constraints:
        alg_name = "grasp|pc"
    script:
        "snake_scripts/joint_dag.py"

rule joint_cstree_distribution:  # untested
    # Estimate a distribution from data
    input:
        input_cstree = rules.cstree_bdeu_parameter_estimation.output
    output:
        full_distr=("full_distr" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_cslearn +
                    "/param_est=/" + pattern_cstree_param_est +
                    "/distr.csv")
    script:
        "scripts/joint_cstree.py"

# Calculate KL divergence between estimated and true distribution
rule kl_div_to_true:
    input:
        true=rules.full_true_cstree_distr.output,
        est=("full_distr" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/{data}" +
                "/alg=/{alg}" +
                "/param_est=/{param_est}" +
                "/distr.csv")
    output:
        kl = ("kl_div" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/{data}" +
                "/alg=/{alg}" +
                "/param_est=/{param_est}" +
                "/kl_div.csv")
    script:
        "scripts/kl_div.py"

""" Plot (2a): comparison of performance of parameter MAP estimate versus parameter MLE est with PC used in Phase 1:

KL-divergence on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:

 - PC-estimated DAG (MLE) for n=10000

 - CSlearn with PC (MLE) for n=250
 - CSlearn with PC (MLE) for n=500
 - CSlearn with PC (MLE) for n=1000
 - CSlearn with PC (MLE) for n=10000

 - CSlearn with PC (MAP) for n=250
 - CSlearn with PC (MAP) for n=500
 - CSlearn with PC (MAP) for n=1000
 - CSlearn with PC (MAP) for n=10000
"""
rule kl_plots_2a_csv:
    input:
        pc = expand(("kl_div" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_pc +
                    "/param_est=/" + pattern_dag_param_est +
                    "/kl_div.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[10000],
                pc_alpha=0.05,
                dag_param_est_alpha=[0.05],
                dag_param_est_estimation_type=["mle"],
                seed=range(1, 11)),

        cslearn_pc = expand(("kl_div" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_pc_cslearn +
                            "/param_est=/" + pattern_cstree_param_est +
                            "/kl_div.csv"),
                    cstree_p=[5,7,10,15],
                    cstree_max_cvar=[2],
                    cstree_prob_cvar=[1],
                    cstree_params_alpha=[0.05],
                    cstree_data_n=[250, 500, 1000, 10000],
                    cslearn_max_cvar=[2],
                    cslearn_prob_cvar=[1],
                    cslearn_mcmc_iterations=[5000],
                    cslearn_alpha_tot=[1.0],
                    cslearn_param_prior=["BDeu"],
                    pc_alpha=0.05,
                    cstree_param_est_alpha=[0.05], # this will be ignored for dag_param_est_type="mle"
                    cstree_param_est_estimation_type=["mle", "map"],
                    seed=range(1, 11))
    output:
        "results/kl_divergence_2a.csv"

    script:
        "rule_scripts/joint_kl.py" # this script will join the csv files


"""
Plot (2b): comparison of performance of parameter MAP estimate versus parameter MLE est with GrASP used in Phase 1:
KL-divergence on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:
- GrASP-estimated DAG (MLE) for n=10000
- CSlearn with GrASP (MAP) for n=250
- CSlearn with GrASP (MAP) for n=500
- CSlearn with GrASP (MAP) for n=1000
- CSlearn with GrASP (MAP) for n=10000
- CSlearn with GrASP (MLE) for n=250
- CSlearn with GrASP (MLE) for n=500
- CSlearn with GrASP (MLE) for n=1000
- CSlearn with GrASP (MLE) for n=10000
"""
rule kl_plots_2b_csv:
    input:
        grasp = expand(("kl_div" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_grasp +
                    "/param_est=/" + pattern_dag_param_est +
                    "/kl_div.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[10000],
                dag_param_est_alpha=[0.05],
                dag_param_est_estimation_type=["mle"],
                seed=range(1, 11)),

        cslearn_grasp = expand(("kl_div" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/param_est=/" + pattern_cstree_param_est +
                                "/kl_div.csv"),
                        cstree_p=[5,7,10,15],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[0.05],
                        cstree_data_n=[250, 500, 1000, 10000],
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        cstree_param_est_alpha=[0.05], # this will be ignored for dag_param_est_type="mle"
                        cstree_param_est_estimation_type=["mle", "map"],
                        seed=range(1, 11))

    output:
        "results/kl_divergence_2b.csv"
    script:
        "rule_scripts/join_kl.py" # this script will join the csv files

"""
Plot (2c): Comparison of CSlearn with other methods:

KL-divergence on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:
    - GrASP-estimated DAG (MLE) for n = 10000
    - CSlearn with GrASP for n = 1000
    - CSlearn with GrASP for n = 10000
    - bos (stagedtrees) with n = 1000
    - GrASP + bhc (stagedtrees) with n = 1000
    - GrASP + bhc (stagedtrees) with n = 10000
* notes:
    - best order search is only done for p = 5,7,10
    - GrASP + bhc is done for p = 5,7,10,15,20
    - bhc = backwards hill climbing
    - bos = best order search
"""
rule kl_plots_2c_csv:
    input:
        grasp = expand(("kl_div" +
            "/true_cstree=/" + pattern_cstree +
            "/true_cstree_params=/" + pattern_cstree_params +
            "/data=/" + pattern_cstree_data +
            "/alg=/" + pattern_grasp +
            "/param_est=/" + pattern_dag_param_est +
            "/kl_div.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[10000],
                dag_param_est_alpha=[0.05],
                dag_param_est_estimation_type=["mle"],
                seed=range(1, 11)),
        cslearn_grasp = expand(("kl_div" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/param_est=/" + pattern_cstree_param_est +
                                "/kl_div.csv"),
                        cstree_p=[5,7,10,15],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[0.05],
                        cstree_data_n=[1000, 10000],
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        cstree_param_est_alpha=[0.05], # this will be ignored for dag_param_est_type="mle"
                        cstree_param_est_estimation_type=["mle"],
                        seed=range(1, 11)),

        bos = expand(("kl_div" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_bos +
                    "/param_est=/" + pattern_st_param_est +
                    "/kl_div.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[1000],
                st_param_est_alpha=[0.05],
                st_param_est_estimation_type=["mle"],
                seed=range(1, 11)),

        grasp_bhc = expand(("kl_div" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_grasp_bhc +
                            "/param_est=/" + pattern_st_param_est +
                            "/kl_div.csv"),
                cstree_p=[5,7,10,15,20],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[1000, 10000],
                st_param_est_alpha=[0.05],
                st_param_est_estimation_type=["mle"],
                seed=range(1, 11)),

    output:
        "results/kl_divergence_2c.csv"
    script:
        "rule_scripts/join_kl.py" # this script will join the csv files
"""
Plot (3a): comparison of runtimes (total times only) for all algorithms on small graphs with multiple sample sizes:

Total Runtime on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:
 - CSlearn with PC for n = 250
 - CSlearn with PC for n = 1000
 - CSlearn with GrASP for n = 250
 - CSlearn with GrASP for n = 1000
 - bos (stagedtrees) with n = 250
 - bos (stagedtrees) with n = 1000
 - GrASP + bhc (stagedtrees) with n = 250
 - GrASP + bhc (stagedtrees) with n = 1000
 """
rule time_plots_3a_csv:
    input:
        cslearn_pc = expand(("time" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_pc_cslearn +
                            "/total_time.csv"),
                    cstree_p=[5,7,10,15],
                    cstree_max_cvar=[2],
                    cstree_prob_cvar=[1],
                    cstree_params_alpha=[0.05],
                    cstree_data_n=[250, 1000],
                    cslearn_max_cvar=[2],
                    cslearn_prob_cvar=[1],
                    cslearn_mcmc_iterations=[5000],
                    cslearn_alpha_tot=[1.0],
                    cslearn_param_prior=["BDeu"],
                    pc_alpha=0.05,
                    seed=range(1, 11)),

        cslearn_grasp = expand(("time" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/total_time.csv"),
                        cstree_p=[5,7,10,15],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[0.05],
                        cstree_data_n=[250, 1000],
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        seed=range(1, 11)),

        bos = expand(("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_bos +
                    "/time.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[250, 1000],
                seed=range(1, 11)),

        grasp_bhc = expand(("time" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_grasp_bhc +
                            "/total_time.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[250, 1000],
                seed=range(1, 11)),
    output:
        "results/time_3a.csv"

"""
Plot (3b): comparison of performance of scalable methods (total times only... I don't think there is much benefit to including the phase breakdown... text me if you want to discuss it):

Total Runtime on y-axis
x-axis: number of nodes (p = 10, 25, 50, 100, 250, 500)
algorithms:
 - CSlearn with PC
 - CSlearn with GrASP
 - GrASP + bhc (stagedtrees)
*notes:
 - number of samples n = 1000
"""

rule time_plots_3b_csv:
    input:
        cslearn_pc = expand(("time" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_pc_cslearn +
                            "/total_time.csv"),
                    cstree_p=[10, 25, 50, 100, 250, 500],
                    cstree_max_cvar=[2],
                    cstree_prob_cvar=[1],
                    cstree_params_alpha=[0.05],
                    cstree_data_n=[1000],
                    pc_alpha=0.05,
                    cslearn_max_cvar=[2],
                    cslearn_prob_cvar=[1],
                    cslearn_mcmc_iterations=[5000],
                    cslearn_alpha_tot=[1.0],
                    cslearn_param_prior=["BDeu"],
                    seed=range(1, 11)),

        cslearn_grasp = expand(("time" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/total_time.csv"),
                        cstree_p=[10, 25, 50, 100, 250, 500],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[0.05],
                        cstree_data_n=[1000],
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        seed=range(1, 11)),

        grasp_bhc = expand(("time" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_grasp_bhc +
                            "/total_time.csv"),
                cstree_p=[10, 25, 50, 100, 250, 500],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[0.05],
                cstree_data_n=[1000],
                seed=range(1, 11))
    output:
        "results/time_3b.csv"

rule time_plots_3a:
    input: "results/time_3a.csv"
    output: "results/time_3a.png"
    script: "rule_scripts/plot_time.py"

rule time_plots_3b:
    input: "results/time_3b.csv"
    output: "results/time_3b.png"
    script: "rule_scripts/plot_time.py"

rule kl_plots_2a:
    input: "results/kl_divergence_2a.csv"
    output: "results/kl_divergence_2a.png"
    script: "rule_scripts/plot_kl.py"

rule kl_plots_2b:
    input: "results/kl_divergence_2b.csv"
    output: "results/kl_divergence_2b.png"
    script: "rule_scripts/plot_kl.py"

rule kl_plots_2c:
    input: "results/kl_divergence_2c.csv"
    output: "results/kl_divergence_2c.png"
    script: "rule_scripts/plot_kl.py"

