# Run by typing:
# snakemake all
# For dry run type:
# snakemake all -n

seed_range = range(1, 2)   # can replace with range(1, 11) after testing

# CStree model
pattern_cstree = "cstree/cstree_p={cstree_p}/cstree_max_cvar={cstree_max_cvar}/cstree_prob_cvar={cstree_prob_cvar}/seed={seed}"
pattern_cstree_params = "true_cstree_params/cstree_params_alpha={cstree_params_alpha}/seed={seed}"
pattern_cstree_data = "data/cstree_data_n={cstree_data_n}/seed={seed}"

# Structure learning
pattern_cslearn = ("cslearn/alg_name={alg_name}/cslearn_poss_cvars={cslearn_poss_cvars}/cslearn_mcmc_iterations={cslearn_mcmc_iterations}/"
                   "cslearn_alpha_tot={cslearn_alpha_tot}/cslearn_param_prior={cslearn_param_prior}/"
                   "cslearn_max_cvar={cslearn_max_cvar}/cslearn_prob_cvar={cslearn_prob_cvar}/seed={seed}")
pattern_grasp = "grasp/alg_name={alg_name}/seed={seed}"
pattern_pc = "pc/alg_name={alg_name}/pc_alpha={pc_alpha}/seed={seed}"
pattern_bos = "bos/alg_name={alg_name}/seed={seed}"
pattern_bhc = "bhc/alg_name={alg_name}/bhc_start_alg={bhc_start_alg}/seed={seed}"

# Structure learning with imposed start algorithm pattern
pattern_grasp_bhc = "bhc/alg_name={alg_name}/bhc_start_alg="+ pattern_grasp +"/seed={seed}"
pattern_pc_bhc = "bhc/alg_name={alg_name}/bhc_start_alg="+pattern_pc +"/seed={seed}"

# With imposed poss_cvars
pattern_pc_cslearn = ("cslearn/alg_name={alg_name}/cslearn_poss_cvars="+pattern_pc+"/cslearn_mcmc_iterations={cslearn_mcmc_iterations}/"
                      "cslearn_alpha_tot={cslearn_alpha_tot}/cslearn_param_prior={cslearn_param_prior}/"
                      "cslearn_max_cvar={cslearn_max_cvar}/cslearn_prob_cvar={cslearn_prob_cvar}/seed={seed}")
pattern_grasp_cslearn = ("cslearn/alg_name={alg_name}/cslearn_poss_cvars="+pattern_grasp+"/cslearn_mcmc_iterations={cslearn_mcmc_iterations}/"
                         "cslearn_alpha_tot={cslearn_alpha_tot}/cslearn_param_prior={cslearn_param_prior}/"
                         "cslearn_max_cvar={cslearn_max_cvar}/cslearn_prob_cvar={cslearn_prob_cvar}/seed={seed}")

# Parameter estimation
pattern_dag_param_est = "dag_param_est/dag_param_est_estimation_type={dag_param_est_estimation_type}/dag_param_est_alpha={dag_param_est_alpha}/seed={seed}" # type is bdeu or mle
pattern_cstree_param_est = "cstree_param_est/cstree_param_est_estimation_type={cstree_param_est_estimation_type}/cstree_param_est_alpha={cstree_param_est_alpha}/seed={seed}" # type is bdeu or mle
pattern_st_param_est = "st_param_est/st_param_est_estimation_type={st_param_est_estimation_type}/st_param_est_alpha={st_param_est_alpha}/seed={seed}" # type is bdeu or mle

# Evaluation
pattern_kl_div = "kl_div"

container: "docker://bpimages/cslearn:1.3.0-arm64"

def input_cvars(wildcards):
    """
    Input for the poss_cvars parameter of the cslearn algorithm
    """

    if wildcards.cslearn_poss_cvars == "None":
        return []
    else:
        # the poss_cvars will be the pattern string of a DAG estimation algorithm
        return ("estimate" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + wildcards.cslearn_poss_cvars +
                "/poss_cvars.json")

def input_alg(wildcards):

    if wildcards.bhc_start_alg == "None":
        return []
    else:
        # the poss_cvars will be the pattern string of a DAG estimation algorithm
        return ("estimate" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + wildcards.bhc_start_alg +
                "/dag.csv") # dag.csv

def input_time_bhc(wildcards):

        if wildcards.bhc_start_alg == "None":
            return []
        else:
            # the poss_cvars will be the pattern string of a DAG estimation algorithm
            return ("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + wildcards.bhc_start_alg +
                    "/time.csv")

def input_time_cslearn(wildcards):

        if wildcards.cslearn_poss_cvars == "None":
            return []
        else:
            # the poss_cvars will be the pattern string of a DAG estimation algorithm
            return ("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + wildcards.cslearn_poss_cvars +
                    "/time.csv")
rule test:
    input:
        #"results/kl_divergence_2c.pdf",
        "results/time_3a.pdf"

rule all:
    input:
        "results/kl_divergence_2a.pdf",
        "results/kl_divergence_2b.pdf",
        "results/kl_divergence_2c.pdf",
        "results/time_3a.pdf",
        "results/time_3b.pdf"

# Reads a DAG (adjacency matrix) and returns a list of possible cvars
# as a JSON file.
rule dag_to_poss_cvar:          # tested
    input:
        "{whatever}/dag.csv" # dag.csv
    output:
        "{whatever}/poss_cvars.json"
    script:
        "snake_scripts/dag_to_poss_cvar.py"

# # Convert a chain graph to a DAG. Eg. if the chain graph is
# # a graph generated by PC or GRASP, then this rule will convert
# # it to a DAG.
# # Grasp outputs acpdag and pc outputs a chaingraph. Maybe I shouldnt
# # make such a deal of this. They are both chain graphs.
# rule chaingraph_to_dag:
#     input:
#         #"{whatever}/alg=/{alg}/{andever}/cg.csv",
#         branch(evaluate("{alg} =='pc'"),
#                then= "{whatever}/alg=/{alg}/{andever}/cg.csv",
#                otherwise= "{whatever}/alg=/{alg}/{andever}/cpdag.csv") # this is grasp
#     output:
#         "{whatever}/alg=/{alg}/{andever}/dag.csv"
#     wildcard_constraints:
#         #alg = "[pc]"
#         alg = "[a-z]+" # wanted to match starting with pc or grasp
#     script:
#         "snake_scripts/chain_to_dag.R" # in the pcalg package this is cextend

rule cstree:                    # tested
    output:
        "true_cstree/"+ pattern_cstree + "/cstree.csv"
    script:
        "snake_scripts/generate_cstree.py"

rule cstree_params:             # tested
    input:
        cstree=rules.cstree.output
    output:
        ("true_cstree_params/"+pattern_cstree_params+
         "/true_cstree/"+ pattern_cstree + "/cstree.csv")
    script:
        "snake_scripts/generate_cstree_params.py"

rule full_true_cstree_distr:    # tested
    input:
        cstree_params=rules.cstree_params.output
    output:
        ("full_true_distr/"+
         pattern_cstree+"/true_cstree_params/"+
         pattern_cstree_params+"/distr.csv")
    script:
        "snake_scripts/full_true_cstree_distr.py"

rule cstree_data:               # tested
    input:
        cstree=rules.cstree_params.output
    output:
        ("data"+
         "/true_cstree=/"+ pattern_cstree +
         "/true_cstree_params=/" + pattern_cstree_params +
         "/data=/"+pattern_cstree_data + "/data.csv")
    script:
        "snake_scripts/simulate_data.py"

rule bos:
    # Use BOS to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        data=rules.cstree_data.output
    output:
        st=("estimate" +
            "/true_cstree=/" + pattern_cstree +
            "/true_cstree_params=/" + pattern_cstree_params +
            "/data=/" + pattern_cstree_data +
            "/alg=/" + pattern_bos +
            "/structure.rds"),
        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_bos +
              "/time.csv")
    container: "docker://bpimages/stagedtrees:2.3.0-arm64"
    script:
        "snake_scripts/estimate_bos.R"

rule bhc:
    # Use BHC to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        data=rules.cstree_data.output,
        input_alg_dag=input_alg,
        input_alg_time=input_time_bhc

    output:
        structure=("estimate" +
                   "/true_cstree=/" + pattern_cstree +
                   "/true_cstree_params=/" + pattern_cstree_params +
                   "/data=/" + pattern_cstree_data +
                   "/alg=/" + pattern_bhc +
                   "/structure.rds"), # This might not be a csv file
        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_bhc +
              "/time.csv"),
        total_time=("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_bhc +
                    "/total_time.csv")        
    container: "docker://bpimages/stagedtrees:2.3.0-arm64"
    script:
        "snake_scripts/estimate_bhc.R"

rule cslearn:                   # tested
    # Estimate a distribution from data
    input:
        data=rules.cstree_data.output,
        poss_cvars=input_cvars, # will be empty if poss_cvars is None
        input_time=input_time_cslearn
    output:
        cstree = ("estimate" +
                  "/true_cstree=/" + pattern_cstree +
                  "/true_cstree_params=/" + pattern_cstree_params +
                  "/data=/" + pattern_cstree_data +
                  "/alg=/" + pattern_cslearn +
                  "/structure.csv"),
        #  add time and total time (including poss_csvars time)
        time = ("time" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + pattern_cslearn +
                "/time.csv"),
        total_time = ("time" +
                      "/true_cstree=/" + pattern_cstree +
                      "/true_cstree_params=/" + pattern_cstree_params +
                      "/data=/" + pattern_cstree_data +
                      "/alg=/" + pattern_cslearn +
                      "/total_time.csv") # this will be same as time if poss_cvars is None
    script:
        "snake_scripts/estimate_cstree.py"

rule grasp:                     # tested
    # Use GRaSP to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        data=rules.cstree_data.output
    output:
        dag=("estimate" +
                   "/true_cstree=/" + pattern_cstree +
                   "/true_cstree_params=/" + pattern_cstree_params +
                   "/data=/" + pattern_cstree_data +
                   "/alg=/" + pattern_grasp +
                   "/dag.csv"),
                   # "/cpdag.csv"),
        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_grasp +
              "/time.csv")
    script:
        "snake_scripts/estimate_grasp.py"

rule pc:               # tested
    # Use PC to learn CPDAG from which poss_cvars and a Markov equiv DAG are selected
    input:
        rules.cstree_data.output
    output:
        dag=("estimate" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/" + pattern_cstree_data +
                "/alg=/" + pattern_pc +
                "/dag.csv"),
                # "/cg.csv"), # should be cg.csv
        time=("time" +
              "/true_cstree=/" + pattern_cstree +
              "/true_cstree_params=/" + pattern_cstree_params +
              "/data=/" + pattern_cstree_data +
              "/alg=/" + pattern_pc +
              "/time.csv")

    script:
        "snake_scripts/estimate_pc.py"

# The parameters fro the dag algorithms should be learned in separate rule,
# as this is done in R for both grasp and pc.
rule dag_bdeu_parameter_estimation:
    input:
        dag = ("estimate" +
                "/true_cstree=/{true_cstree}" +
                "/true_cstree_params=/{true_cstree_params}"
                "/data=/{data}" +
                "/alg=/{alg}" +
                "/dag.csv") # should be dag.csv
    output:
        dag_param_est=("dag_param_est" +
                       "/true_cstree=/{true_cstree}" +
                       "/true_cstree_params=/{true_cstree_params}" +
                       "/data=/{data}" +
                       "/alg=/{alg}" +
                       "/param_est=/"+pattern_dag_param_est +
                       "/params.csv")

# CS-BDeu
rule cstree_bdeu_parameter_estimation:
    input:
        cstree = rules.cslearn.output,
        data = rules.cstree_data.output
    output:
        param_est=("cstree_param_est" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_cslearn +
                    "/param_est=/"+pattern_cstree_param_est+
                    "/cstree.csv")
    container: "docker://bpimages/stagedtrees:2.3.0-arm64"
    script:
        "scripts/cstree_bdeu_parameter_estimation.R"

rule stagedtree_ml_parameter_estimation:
    input:
        ("estimate" +
        "/true_cstree=/" + pattern_cstree +
        "/true_cstree_params=/" + pattern_cstree_params +
        "/data=/" + pattern_cstree_data +
        "/alg=/{alg}" +
        "/structure.csv")
    output:
        param_est=("stagedtree_param_est" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/{alg}" +
                    "/param_est=/"+pattern_st_param_est+"/st.rds")
    container: "docker://bpimages/stagedtrees:2.3.0-arm64"

    script:
        "snake_scripts/stagedtree_ml_parameter_estimation.R"

rule joint_stagedtree_distribution:
    input: # this coud be either bhc or bos
        input_st = ("stagedtree_param_est" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg_parameters}" +
                    "/param_est=/{param_est}" +
                    "/st.rds")
    output:
        full_distr=("full_distr" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg_parameters}" +
                    "/param_est=/{param_est}" +
                    "/distr.csv") # this needs to be matched better
    wildcard_constraints:
        alg_name = "bos|bhc"
    container: "docker://bpimages/stagedtrees:2.3.0-arm64"
    script:
        "snake_scripts/joint_stagedtree_distr.R"

rule joint_dag_distribution:    # tested
    # Estimate a distribution from data
    input:
        input_bn = ("dag_param_est" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg}" +
                    "/param_est=/{param_est}" +
                    "/params.csv")
    output:
        full_distr=("full_distr" +
                    "/true_cstree=/{true_cstree}" +
                    "/true_cstree_params=/{true_cstree_params}" +
                    "/data=/{data}" +
                    "/alg=/{alg_name}/{alg}" +
                    "/param_est=/{param_est}" +
                    "/distr.csv")
    wildcard_constraints:
        alg_name = "grasp|pc"
    script:
        "snake_scripts/joint_dag.py"

rule joint_cstree_distribution:
    # Estimate a distribution from data
    input:
        input_cstree = rules.cstree_bdeu_parameter_estimation.output
    output:
        full_distr=("full_distr" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_cslearn +
                    "/param_est=/" + pattern_cstree_param_est +
                    "/distr.csv")
    script:
        "scripts/joint_cstree.py"

# Calculate KL divergence between estimated and true distribution
rule kl_div_to_true:
    input:
        true=rules.full_true_cstree_distr.output,
        est=("full_distr" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/{data}" +
                "/alg=/{alg}" +
                "/param_est=/{param_est}" +
                "/distr.csv")
    output:
        kl = ("kl_div" +
                "/true_cstree=/" + pattern_cstree +
                "/true_cstree_params=/" + pattern_cstree_params +
                "/data=/{data}" +
                "/alg=/{alg}" +
                "/param_est=/{param_est}" +
                "/kl_div.csv")
    script:
        "scripts/kl_div.py"

""" Plot (2a): comparison of performance of parameter MAP estimate versus parameter MLE est with PC used in Phase 1:

KL-divergence on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:

 - PC-estimated DAG (MLE) for n=10000

 - CSlearn with PC (MLE) for n=250
 - CSlearn with PC (MLE) for n=500
 - CSlearn with PC (MLE) for n=1000
 - CSlearn with PC (MLE) for n=10000

 - CSlearn with PC (MAP) for n=250
 - CSlearn with PC (MAP) for n=500
 - CSlearn with PC (MAP) for n=1000
 - CSlearn with PC (MAP) for n=10000
"""
rule kl_plots_2a_csv:
    input:
        pc = expand(("kl_div" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_pc +
                    "/param_est=/" + pattern_dag_param_est +
                    "/kl_div.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[1.0],
                cstree_data_n=[10000],
                pc_alpha=0.05,
                alg_name="pc",
                dag_param_est_alpha=[0.05],
                dag_param_est_estimation_type=["mle"],
                seed=seed_range),

        cslearn_pc = expand(("kl_div" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_pc_cslearn +
                            "/param_est=/" + pattern_cstree_param_est +
                            "/kl_div.csv"),
                    cstree_p=[5,7,10,15],
                    cstree_max_cvar=[2],
                    cstree_prob_cvar=[1],
                    cstree_params_alpha=[1.0],
                    cstree_data_n=[250, 500, 1000, 10000],
                    alg_name="cslearn",
                    cslearn_max_cvar=[2],
                    cslearn_prob_cvar=[1],
                    cslearn_mcmc_iterations=[5000],
                    cslearn_alpha_tot=[1.0],
                    cslearn_param_prior=["BDeu"],
                    pc_alpha=0.05,
                    cstree_param_est_alpha=[0.05], # this will be ignored for dag_param_est_type="mle"
                    cstree_param_est_estimation_type=["mle", "map"],
                    seed=seed_range)
    output:
        "results/kl_divergence_2a.csv"

    script:
        "rule_scripts/join_kl.py" # this script will join the csv files


"""
Plot (2b): comparison of performance of parameter MAP estimate versus parameter MLE est with GrASP used in Phase 1:
KL-divergence on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:
- GrASP-estimated DAG (MLE) for n=10000
- CSlearn with GrASP (MAP) for n=250
- CSlearn with GrASP (MAP) for n=500
- CSlearn with GrASP (MAP) for n=1000
- CSlearn with GrASP (MAP) for n=10000
- CSlearn with GrASP (MLE) for n=250
- CSlearn with GrASP (MLE) for n=500
- CSlearn with GrASP (MLE) for n=1000
- CSlearn with GrASP (MLE) for n=10000
"""
rule kl_plots_2b_csv:
    input:
        grasp = expand(("kl_div" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_grasp +
                    "/param_est=/" + pattern_dag_param_est +
                    "/kl_div.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[1.0],
                cstree_data_n=[10000],
                alg_name="grasp",
                dag_param_est_alpha=[0.05],
                dag_param_est_estimation_type=["mle"],
                seed=seed_range),

        cslearn_grasp = expand(("kl_div" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/param_est=/" + pattern_cstree_param_est +
                                "/kl_div.csv"),
                        cstree_p=[5,7,10,15],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[1.0],
                        cstree_data_n=[250, 500, 1000, 10000],
                        alg_name="cslearn",
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        cstree_param_est_alpha=[0.05], # this will be ignored for dag_param_est_type="mle"
                        cstree_param_est_estimation_type=["mle", "map"],
                        seed=seed_range)

    output:
        "results/kl_divergence_2b.csv"
    script:
        "rule_scripts/join_kl.py" # this script will join the csv files

"""
Plot (2c): Comparison of CSlearn with other methods:

KL-divergence on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:
    - GrASP-estimated DAG (MLE) for n = 10000
    - CSlearn with GrASP for n = 1000
    - CSlearn with GrASP for n = 10000
    - bos (stagedtrees) with n = 1000
    - GrASP + bhc (stagedtrees) with n = 1000
    - GrASP + bhc (stagedtrees) with n = 10000
* notes:
    - best order search is only done for p = 5,7,10
    - GrASP + bhc is done for p = 5,7,10,15,20
    - bhc = backwards hill climbing
    - bos = best order search
"""
rule kl_plots_2c_csv:
    input:
        grasp = expand(("kl_div" +
            "/true_cstree=/" + pattern_cstree +
            "/true_cstree_params=/" + pattern_cstree_params +
            "/data=/" + pattern_cstree_data +
            "/alg=/" + pattern_grasp +
            "/param_est=/" + pattern_dag_param_est +
            "/kl_div.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[1.0],
                cstree_data_n=[10000],
                alg_name="grasp",
                dag_param_est_alpha=[0.05],
                dag_param_est_estimation_type=["mle"],
                seed=seed_range),
        cslearn_grasp = expand(("kl_div" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/param_est=/" + pattern_cstree_param_est +
                                "/kl_div.csv"),
                        cstree_p=[5,7,10,15],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[1.0],
                        cstree_data_n=[1000, 10000],
                        alg_name="cslearn",
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        cstree_param_est_alpha=[0.05], # this will be ignored for dag_param_est_type="mle"
                        cstree_param_est_estimation_type=["mle"],
                        seed=seed_range),

        # bos = expand(("kl_div" +
        #             "/true_cstree=/" + pattern_cstree +
        #             "/true_cstree_params=/" + pattern_cstree_params +
        #             "/data=/" + pattern_cstree_data +
        #             "/alg=/" + pattern_bos +
        #             "/param_est=/" + pattern_st_param_est +
        #             "/kl_div.csv"),
        #         cstree_p=[5,7,10,15],
        #         alg_name="bos",
        #         cstree_max_cvar=[2],
        #         cstree_prob_cvar=[1],
        #         cstree_params_alpha=[1.0],
        #         cstree_data_n=[1000],
        #         st_param_est_alpha=[0.05],
        #         st_param_est_estimation_type=["mle"],
        #         seed=seed_range),

        # grasp_bhc = expand(("kl_div" +
        #                     "/true_cstree=/" + pattern_cstree +
        #                     "/true_cstree_params=/" + pattern_cstree_params +
        #                     "/data=/" + pattern_cstree_data +
        #                     "/alg=/" + pattern_grasp_bhc +
        #                     "/param_est=/" + pattern_st_param_est +
        #                     "/kl_div.csv"),
        #         cstree_p=[5,7,10,15,20],
        #         alg_name="grasp",
        #         cstree_max_cvar=[2],
        #         cstree_prob_cvar=[1],
        #         cstree_params_alpha=[1.0],
        #         cstree_data_n=[1000, 10000],
        #         st_param_est_alpha=[0.05],
        #         st_param_est_estimation_type=["mle"],
        #         seed=seed_range),

    output:
        "results/kl_divergence_2c.csv"
    script:
        "rule_scripts/join_kl.py" # this script will join the csv files

"""
Plot (3a): comparison of runtimes (total times only) for all algorithms on small graphs with multiple sample sizes:

Total Runtime on y-axis
x-axis: number of nodes (p = 5,7,10,15,20)
algorithms:
 - CSlearn with PC for n = 250
 - CSlearn with PC for n = 1000
 - CSlearn with GrASP for n = 250
 - CSlearn with GrASP for n = 1000
 - bos (stagedtrees) with n = 250
 - bos (stagedtrees) with n = 1000
 - GrASP + bhc (stagedtrees) with n = 250
 - GrASP + bhc (stagedtrees) with n = 1000
 """
rule time_plots_3a_csv:         # test
    input:
        cslearn_pc = expand(("time" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_pc_cslearn +
                            "/total_time.csv"),
                    cstree_p=[5,7,10,15],
                    cstree_max_cvar=[2],
                    cstree_prob_cvar=[1],
                    cstree_params_alpha=[1.0],
                    cstree_data_n=[250, 1000],
                    alg_name="cslearn",
                    cslearn_max_cvar=[2],
                    cslearn_prob_cvar=[1],
                    cslearn_mcmc_iterations=[5000],
                    cslearn_alpha_tot=[1.0],
                    cslearn_param_prior=["BDeu"],
                    pc_alpha=0.05,
                    seed=seed_range),

        cslearn_grasp = expand(("time" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/total_time.csv"),
                        cstree_p=[5,7,10,15],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[1.0],
                        cstree_data_n=[250, 1000],
                        alg_name="cslearn",
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        seed=seed_range),
        bos = expand(("time" +
                    "/true_cstree=/" + pattern_cstree +
                    "/true_cstree_params=/" + pattern_cstree_params +
                    "/data=/" + pattern_cstree_data +
                    "/alg=/" + pattern_bos +
                    "/time.csv"),
                cstree_p=[5,7],#[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[1.0],
                cstree_data_n=[250, 1000],
                alg_name="bos",
                seed=seed_range),

        grasp_bhc = expand(("time" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_grasp_bhc +
                            "/total_time.csv"),
                cstree_p=[5,7,10,15],
                cstree_max_cvar=[2],
                cstree_prob_cvar=[1],
                cstree_params_alpha=[1.0],
                cstree_data_n=[250, 1000],
                alg_name="bhc",
                seed=seed_range),
    output:
        "results/time_3a.csv"
    script:
        "rule_scripts/join_time.py" # this script will join the csv files

"""
Plot (3b): comparison of performance of scalable methods (total times only... I don't think there is much benefit to including the phase breakdown... text me if you want to discuss it):

Total Runtime on y-axis
x-axis: number of nodes (p = 10, 25, 50, 100, 250, 500)
algorithms:
 - CSlearn with PC
 - CSlearn with GrASP
 - GrASP + bhc (stagedtrees)
*notes:
 - number of samples n = 1000
"""

rule time_plots_3b_csv:
    input:
        cslearn_pc = expand(("time" +
                            "/true_cstree=/" + pattern_cstree +
                            "/true_cstree_params=/" + pattern_cstree_params +
                            "/data=/" + pattern_cstree_data +
                            "/alg=/" + pattern_pc_cslearn +
                            "/total_time.csv"),
                    cstree_p=[10, 25, 50, 100, 250, 500],
                    cstree_max_cvar=[2],
                    cstree_prob_cvar=[1],
                    cstree_params_alpha=[1.0],
                    cstree_data_n=[1000],
                    pc_alpha=0.05,
                    alg_name="cslearn",
                    cslearn_max_cvar=[2],
                    cslearn_prob_cvar=[1],
                    cslearn_mcmc_iterations=[5000],
                    cslearn_alpha_tot=[1.0],
                    cslearn_param_prior=["BDeu"],
                    seed=seed_range),

        cslearn_grasp = expand(("time" +
                                "/true_cstree=/" + pattern_cstree +
                                "/true_cstree_params=/" + pattern_cstree_params +
                                "/data=/" + pattern_cstree_data +
                                "/alg=/" + pattern_grasp_cslearn +
                                "/total_time.csv"),
                        cstree_p=[10, 25, 50, 100, 250, 500],
                        cstree_max_cvar=[2],
                        cstree_prob_cvar=[1],
                        cstree_params_alpha=[1.0],
                        cstree_data_n=[1000],
                        alg_name="cslearn",
                        cslearn_max_cvar=[2],
                        cslearn_prob_cvar=[1],
                        cslearn_mcmc_iterations=[5000],
                        cslearn_alpha_tot=[1.0],
                        cslearn_param_prior=["BDeu"],
                        seed=seed_range),

        # grasp_bhc = expand(("time" +
        #                     "/true_cstree=/" + pattern_cstree +
        #                     "/true_cstree_params=/" + pattern_cstree_params +
        #                     "/data=/" + pattern_cstree_data +
        #                     "/alg=/" + pattern_grasp_bhc +
        #                     "/total_time.csv"),
        #         cstree_p=[10, 25, 50, 100, 250, 500],
        #         cstree_max_cvar=[2],
        #         cstree_prob_cvar=[1],
        #         cstree_params_alpha=[1.0],
        #         cstree_data_n=[1000],
        #         alg_name="bhc",
        #         seed=seed_range)
    output:
        "results/time_3b.csv"
    script:
        "rule_scripts/join_time.py" # this script will join the csv files

rule kl_plots_2a:
    input: "results/kl_divergence_2a.csv"
    output: "results/kl_divergence_2a.pdf"
    script: "rule_scripts/plot_kl.py"

rule kl_plots_2b:
    input: "results/kl_divergence_2b.csv"
    output: "results/kl_divergence_2b.pdf"
    script: "rule_scripts/plot_kl.py"

rule kl_plots_2c:
    input: "results/kl_divergence_2c.csv"
    output: "results/kl_divergence_2c.pdf"
    script: "rule_scripts/plot_kl.py"

rule time_plots_3a:             # tested
    input: "results/time_3a.csv"
    output: "results/time_3a.pdf"
    script: "rule_scripts/plot_time.py"

rule time_plots_3b:
    input: "results/time_3b.csv"
    output: "results/time_3b.pdf"
    script: "rule_scripts/plot_time.py"
